name: Update stars
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download GitHub Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: sort-awesome-lists/releases
          tag: v0.0.1
          file: sort-awesome-lists
      - run: |
          ls
          sed -r -i 's/- \*\*[[:digit:]]+\*\* /- /g' README.md
          ./sort-awesome-lists -t={{ secrets.GITHUB_TOKEN }} -o=README.md.1 README.md
          rm -f README.md
          mv README.md.1 README.md
          ls
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: \{{ secrets.GITHUB_TOKEN }}
